import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/provider/ReduxProvider";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Feedme | Healthy Meal Always",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Before rendering anything, inject a script to set cloudinary config
  const cloudinaryScript = `
    window.__NEXT_CLOUDINARY_CONFIG__ = {
      cloudName: "dciqyeuyp"
    };
  `;

  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: cloudinaryScript }} />
      </head>
      <body className={`${fredoka.variable} antialiased`}>
        <Toaster position="top-right" />
        <ReduxProvider>
          <Providers>{children}</Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
